# Generated by Django 4.2 on 2025-12-24 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('setup_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cycle_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='production_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='scrap_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bomline',
            name='scrap_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='completed_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='rejected_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_orders', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.workcenter'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='capacity_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('partially_completed', 'Partially Completed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('planned_start', models.DateTimeField()),
                ('planned_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_good', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('setup_time_actual', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('run_time_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.operation')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.productionorder')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workcenter'),
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_issued', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_used', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('quantity_returned', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bom_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.bomline')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_materials', to=settings.AUTH_USER_MODEL)),
                ('issued_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionorder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bomline',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.operation'),
        ),
    ]
