# Generated by Django 4.2 on 2025-12-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pass_number', models.CharField(max_length=50, unique=True)),
                ('pass_type', models.CharField(choices=[('material_in', 'Material Incoming'), ('material_out', 'Material Outgoing'), ('vehicle_in', 'Vehicle Incoming'), ('vehicle_out', 'Vehicle Outgoing'), ('personnel_in', 'Personnel Incoming'), ('personnel_out', 'Personnel Outgoing'), ('visitor', 'Visitor'), ('contractor', 'Contractor'), ('tools_equipment', 'Tools/Equipment'), ('waste_scrap', 'Waste/Scrap')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('person_name', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField()),
                ('expected_in_date', models.DateTimeField(blank=True, null=True)),
                ('expected_out_date', models.DateTimeField(blank=True, null=True)),
                ('actual_in_date', models.DateTimeField(blank=True, null=True)),
                ('actual_out_date', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('security_remarks', models.TextField(blank=True)),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(blank=True, max_length=200)),
                ('is_returnable', models.BooleanField(default=False)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('reference_document', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='gate_passes/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes_approved', to='hr.employee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('requesting_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes_requested', to='hr.employee')),
                ('security_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes_security', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_company', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('purpose', models.TextField()),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('visitor_card_issued', models.CharField(blank=True, max_length=50)),
                ('visitor_card_returned', models.BooleanField(default=False)),
                ('gate_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.gatepass')),
                ('security_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visiting_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='GatePassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='security.gatepass')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='GatePassApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee')),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='security.gatepass')),
            ],
            options={
                'unique_together': {('gate_pass', 'approval_level')},
            },
        ),
    ]
