# Generated by Django 4.2 on 2025-12-24 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_operation_billofmaterials_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qc_number', models.CharField(max_length=50, unique=True)),
                ('qc_type', models.CharField(choices=[('incoming', 'Incoming Material'), ('in_process', 'In-Process'), ('final', 'Final Inspection'), ('outgoing', 'Outgoing')], max_length=20)),
                ('reference_type', models.CharField(choices=[('production', 'Production Order'), ('purchase', 'Purchase Order'), ('other', 'Other')], max_length=20)),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('quarantine', 'Quarantine')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.goodsreceiptitem')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productionorder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualityParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameter_type', models.CharField(choices=[('visual', 'Visual'), ('dimensional', 'Dimensional'), ('physical', 'Physical'), ('chemical', 'Chemical'), ('performance', 'Performance')], max_length=20)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], default='na', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.qualityparameter')),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.qualitycheck')),
            ],
        ),
        migrations.CreateModel(
            name='NonConformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ncr_number', models.CharField(max_length=50, unique=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigation', 'Under Investigation'), ('corrective', 'Corrective Action'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.qualitycheck')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncr_responsible', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
